# Generated by Django 4.2.4 on 2023-09-01 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Em análise', 'Em análise'), ('Aprovada', 'Aprovada'), ('Negada', 'Negada')], default='Em análise', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CampoInformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=200)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='propostas.proposta')),
            ],
        ),
    ]
