# Generated by Django 4.2.4 on 2023-09-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0002_delete_campoinformacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('campos', models.JSONField()),
            ],
        ),
    ]
