# Generated by Django 4.2.4 on 2023-09-01 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0004_alter_proposta_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.TextField()),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propostas.proposta')),
            ],
        ),
        migrations.DeleteModel(
            name='ConfiguracaoCampos',
        ),
    ]
